While 1
	
	$x = RANDOM(850,866)
	$y = RANDOM(435,455)
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(934,954),RANDOM(469,483),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(934,960),RANDOM(612,640),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1020,1045),RANDOM(446,464),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(954,980),RANDOM(632,660),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1050,1075),RANDOM(466,484),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(954,980),RANDOM(632,660),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1050,1075),RANDOM(466,484),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(964,990),RANDOM(632,660),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	
	
	#####Second8
	
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(1000,2000))
	MouseMOVE(RANDOM(1141,1177),RANDOM(466,484),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(1000,2000))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(1000,1550))
	MouseMOVE(RANDOM(999,1030),RANDOM(644,673),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1050,1075),RANDOM(466,484),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(954,980),RANDOM(652,670),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1040,1085),RANDOM(471,497),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(964,980),RANDOM(637,665),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(1045,1070),RANDOM(471,489),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	MouseMOVE($x,$y,Random(4,10))
	MouseClick("left",$x,$y,1,Random(5-10))
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(954,980),RANDOM(637,665),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(700,1550))
	
	
	###########Reset for Watering
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(253,264),RANDOM(446,466),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(8500,9050))
	
	MouseMOVE(RANDOM(905,925),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2100,2150))
	
	MouseMOVE(RANDOM(990,1010),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	######SECOND 8 Water#############
	
	MouseMOVE(RANDOM(1143,1163),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(3000,3150))

	MouseMOVE(RANDOM(1005,1025),RANDOM(647,667),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
		MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
		###########Reset for Watering
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(253,264),RANDOM(446,466),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(8500,9050))
	
	MouseMOVE(RANDOM(905,925),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2100,2150))
	
	MouseMOVE(RANDOM(990,1010),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	######SECOND 8 Water#############
	
	MouseMOVE(RANDOM(1143,1163),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(3000,3150))

	MouseMOVE(RANDOM(1005,1025),RANDOM(647,667),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
		MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
		###########Reset for Watering
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(253,264),RANDOM(446,466),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(8500,9050))
	
	MouseMOVE(RANDOM(905,925),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2100,2150))
	
	MouseMOVE(RANDOM(990,1010),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	######SECOND 8 Water#############
	
	MouseMOVE(RANDOM(1143,1163),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(3000,3150))

	MouseMOVE(RANDOM(1005,1025),RANDOM(647,667),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
		MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
		###########Reset for Watering
	Sleep(Random(700,1550))
	MouseMOVE(RANDOM(253,264),RANDOM(446,466),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(8500,9050))
	
	MouseMOVE(RANDOM(905,925),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2100,2150))
	
	MouseMOVE(RANDOM(990,1010),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1074),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(967,987),RANDOM(615,635),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	######SECOND 8 Water#############
	
	MouseMOVE(RANDOM(1143,1163),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(3000,3150))

	MouseMOVE(RANDOM(1005,1025),RANDOM(647,667),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2700,2750))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
	MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))
	
		MouseMOVE(RANDOM(1054,1069),RANDOM(449,467),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	MouseMOVE(RANDOM(967,987),RANDOM(614,634),Random(4,10))
	$spot = MouseGetPos()
	MouseClick("left",$spot[0],$spot[1],1,Random(5-10))
	Sleep(Random(2500,2550))

	
WEnd